version: "3.3"

services:
  i2-init:
    image: smartbcity/i2-init:experimental
    network_mode: host
    environment:
      - i2_keycloak_auth-server-url=http://localhost:8080/auth
      - i2_keycloak_username=admin
      - i2_keycloak_password=admin
      - i2_init_realm=im-test
      - i2_init_admin-user_username=im-admin
      - i2_init_admin-user_password=!tesTTest!
      - i2_init_admin-user_email=admin@smart-b.io
      - i2_init_admin-user_firstname=admin
      - i2_init_admin-user_lastname=im
      - i2.init.admin-client=im-test-client
      - i2.init.admin-client-secret=secret

