server:
  port: 8009

spring:
  main:
    web-application-type: reactive
#  data:
#     redis:
#      password: redis
  cache:
    cache-names: "organization, user"


i2:
  issuers:
    -
      name: auth-test
      authUrl: http://keycloak-it:8080/auth
      realm: im-test
      im:
        clientId: im-test-client
        clientSecret: secret

connect:
  im:
    user:
      action:
        useJwtClientId: true
    organization:
      insee:
        token: ${INSEE_TOKEN}
        sireneApi: https://api.insee.fr/entreprises/sirene/V3

---
spring:
  config:
    activate:
      on-profile: local

#fs:
#  url: http://localhost:8090

i2:
  issuers:
    -
      name: local
      authUrl: https://auth.smart-b.io/auth
      realm: test
      im:
        clientId: i2-api
        clientSecret: e44dbaf6-d9af-4234-9a30-3a481c96e157
