server:
  port: 8009

spring:
  main:
    web-application-type: reactive
#  data:
#     redis:
#      password: redis
  cache:
    cache-names: "organization, user"

i2:
  issuers:
    -
      name: master
      authUrl: http://keycloak-it:8080
      realm: master
      im:
        clientId: im-root
        clientSecret: 2rc3Aay1ssJgY946tFeacnOMfUm9M0tJ

connect:
  fs: http://fs:8090
  im:
    user:
      action:
        useJwtClientId: true
    organization:
      insee:
        token: ${INSEE_TOKEN}
        sireneApi: https://api.insee.fr/entreprises/sirene/V3
    smtp:
        host: connect-fake-smtp,
        port: 1025,
        from: noreply@smartb.city,
        ssl: false,
        starttls: false,
        auth: false
trace: true
---
spring:
  config:
    activate:
      on-profile: local

#fs:
#  url: http://localhost:8090

i2:
  issuers:
    -
      name: local
      authUrl: https://auth.smart-b.io/auth
      realm: test
      im:
        clientId: i2-api
        clientSecret: e44dbaf6-d9af-4234-9a30-3a481c96e157
