spring:
  main:
    web-application-type: reactive

i2:
  organization:
    insee:
      token: ${INSEE_TOKEN}
      sirene-api: https://api.insee.fr/entreprises/sirene/V3
  issuers:
    -
      uri: http://localhost:8080/auth/realms/test
      authUrl: http://localhost:8080/auth
      realm: test
      clientId: i2-api
      clientSecret: cc7c636d-cfbc-4cf2-9a59-a4f759893966
    -
      uri: http://localhost:8080/auth/realms/test2
      authUrl: http://localhost:8080/auth
      realm: test2
      clientId: i2-api
      clientSecret: 5e471884-ab65-4b84-a20b-6d16a77aa553

server:
  port : 8009
