server:
  port : 8010


# Application authentication
# A pair of clientId/secret per app
keycloak:
  authUrl: https://auth.tracabois.smart-b.io/auth
  realm: test
  clientId: i2-api
  clientSecret: ab7a340d-bffe-445a-a021-3ec10d380153


# Where to reach IM
im: http://localhost:8009


# Config needed when importing organization-api as it requires
# the config to reach Insee for organizationGetFromInsee function
i2:
  organization:
    insee:
      token: ${INSEE_TOKEN}
      sirene-api: https://api.insee.fr/entreprises/sirene/V3