server:
  port: 1000

im:
  script:
    retry:
      max: 5
      delayMillis: 10000
    config:
      retry:
        max: ${im.script.retry.max}
        delayMillis: ${im.script.retry.delayMillis}
#      json: file:./infra/docker-compose/config/config.json
    init:

      retry:
        max: ${im.script.retry.max}
        delayMillis: ${im.script.retry.delayMillis}
#      json: file:./infra/docker-compose/config/init.json

f2:
  tenant:
    issuerBaseUri: http://localhost:8080

connect:
  im:
    keycloak:
      url: http://localhost:8080
      realm: master
      clientId: im-test-client
      clientSecret: secret

---
spring:
  config:
    activate:
      on-profile: dev

im:
  script:
    config:
        auth:
            serverUrl: http://localhost:8080
            realmId: master
            clientId: im-app
            client-Secret: secret
        json: file:./infra/docker-compose/config/build/config.json
    init:
        auth:
            serverUrl: http://localhost:8080
            username: root
            password: root
            realmId: master
            clientId: admin-cli
        json: file:./infra/docker-compose/config/build/init.json
