server:
  port: 1000

im:
  script:
    retry:
      max: 5
      delayMillis: 10000
    config:
      retry:
        max: ${im.script.retry.max}
        delayMillis: ${im.script.retry.delayMillis}
#      json: file:./infra/docker-compose/config/config.json
    init:

      retry:
        max: ${im.script.retry.max}
        delayMillis: ${im.script.retry.delayMillis}
#      json: file:./infra/docker-compose/config/init.json

i2:
  issuers:

---
spring:
  config:
    activate:
      on-profile: dev

im:
  script:
    config:
        auth:
            serverUrl: http://keycloak-it:8080
            realmId: im-test
            clientId: im-test-client
            client-Secret: secret
        json: file:./infra/docker-compose/config/build/config.json
    init:
        auth:
            serverUrl: http://keycloak-it:8080
            username: root
            password: root
            realmId: master
            clientId: admin-cli
        json: file:./infra/docker-compose/config/build/init.json
