server:
  port: 1000

im:
  script:
    retry:
      max: 5
      delayMillis: 10000
    config:
      auth:
        serverUrl: http://keycloak-it:8080
        realmId: im-test
        clientId: im-test-client
        client-Secret: secret
      retry:
        max: ${im.script.retry.max}
        delayMillis: ${im.script.retry.delayMillis}
#      json: file:./infra/docker-compose/config/config.json
    init:
      auth:
        serverUrl: http://keycloak-it:8080
        username: root
        password: root
        realmId: master
        clientId: admin-cli
      retry:
        max: ${im.script.retry.max}
        delayMillis: ${im.script.retry.delayMillis}
#      json: file:./infra/docker-compose/config/init.json

i2:
  issuers:

---
spring:
  config:
    activate:
      on-profile: dev

im:
  script:
    config:
      json: file:./infra/docker-compose/config/build/config.json
      auth:
        serverUrl: http://localhost:8080
        realmId: im-local
    init:
      json: file:./infra/docker-compose/config/build/init.json
      auth:
        serverUrl: http://localhost:8080
