spring:
  main:
    web-application-type: none

im:
  keycloak:
    serverUrl: http://keycloak-it:8080/auth
    realm: test
    clientId: i2-test-client
    client-Secret: secret
  config:
    maxRetries: 5
    retryDelayMillis: 10000
    json: file:./infra/docker-compose/config.json
