version: "3.7"

services:
  im-keycloak:
    image: smartbcity/im-keycloak:next
    container_name: ${KC_HOSTNAME}
    environment:
      KC_DB_URL: 'jdbc:postgresql://im-keycloak-postgres/im-keycloak'
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: admin
      KC_DB_SCHEMA: public
      KC_HOSTNAME: localhost:8080
      KEYCLOAK_ADMIN: ${KC_ROOT_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ROOT_PASS}
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "ssl=false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - '8080:8080'
    networks:
      - net
    depends_on:
      - im-keycloak-postgres

  im-keycloak-postgres:
    image: postgres
    container_name: im-keycloak-postgres
    environment:
      POSTGRES_DB: im-keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
