version: "3.7"
services:
  im-init:
    image: smartbcity/im-script:${VERSION_IM}
    container_name: im-init
    environment:
      - im_script_init_auth_serverUrl=${AUTH_HOST_URL}
      - im_script_init_auth_username=${KC_ROOT_USER}
      - im_script_init_auth_password=${KC_ROOT_PASS}
      - im_script_init_json=file:/tmp/init.json
    volumes:
      - ./config/build/init.json:/tmp/init.json
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
