spring:
  main:
    web-application-type: none

im:
  keycloak:
    serverUrl: http://keycloak-it:8080/auth
    realm: master
    username: root
    password: root
    clientId: admin-cli
  init:
    maxRetries: 5
    retryDelayMillis: 10000
    json: file:./infra/docker-compose/init.json
